<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7" />
		<PackageVersion Include="MediatR" Version="14.1.0" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7" />
		<PackageVersion Include="SendGrid" Version="9.29.3" />
		<PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.7" />
		<PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>
</Project>