FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY Directory.Packages.props .
COPY Directory.Build.props .
COPY SourceBase.Domain/SourceBase.Domain.csproj SourceBase.Domain/
COPY SourceBase.Application/SourceBase.Application.csproj SourceBase.Application/
COPY SourceBase.EmailWorker/SourceBase.EmailWorker.csproj SourceBase.EmailWorker/
RUN dotnet restore SourceBase.EmailWorker/SourceBase.EmailWorker.csproj

COPY SourceBase.Domain/ SourceBase.Domain/
COPY SourceBase.Application/ SourceBase.Application/
COPY SourceBase.EmailWorker/ SourceBase.EmailWorker/

RUN dotnet publish SourceBase.EmailWorker/SourceBase.EmailWorker.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "SourceBase.EmailWorker.dll"]
