FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

RUN dotnet workload install wasm-tools

COPY Directory.Packages.props .
COPY Directory.Build.props .
COPY SourceBase.Web/SourceBase.Web.csproj SourceBase.Web/
RUN dotnet restore SourceBase.Web/SourceBase.Web.csproj

COPY . .

ARG API_URL
RUN echo "{\"ApiBaseUrl\":\"${API_URL}\"}" > SourceBase.Web/wwwroot/appsettings.Production.json

RUN dotnet publish SourceBase.Web/SourceBase.Web.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
RUN apk upgrade --no-cache
COPY --from=build /app/publish/wwwroot /usr/share/nginx/html
COPY nginx.web.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
