<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SourceBase.Api\SourceBase.Api.csproj" />
		<ProjectReference Include="..\SourceBase.Web\SourceBase.Web.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.NodeJs" />
		<PackageReference Include="MessagePack" />
	</ItemGroup>

</Project>