<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>SourceBase.Infrastructure</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
		<PackageReference Include="SendGrid" Version="9.29.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SourceBase.Application\SourceBase.Application.csproj" />
	</ItemGroup>

</Project>
