<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>SourceBase.Application</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SourceBase.Domain\SourceBase.Domain.csproj" />
	</ItemGroup>
</Project>
