@HostAddress = https://localhost:7237

POST {{HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "aloha@yopmail.com",
  "password": "Hello@123"
}

###

POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "aloha@yopmail.com",
  "password": "Hello@123"
}

###

GET {{HostAddress}}/api/auth/info
Accept: application/json
Authorization: Bearer {{accessToken}}

###

POST {{HostAddress}}/api/auth/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "firstName": "Steven - 9",
  "lastName": "Aloha - 1"
}


###

GET {{HostAddress}}/api/todo
Accept: application/json
Authorization: Bearer {{accessToken}}

###

POST {{HostAddress}}/api/todo
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Task 5",
  "date": "2024-03-30"
}

###


DELETE {{HostAddress}}/api/todo/e839c288-9356-451f-ed99-08dc3c2576db
Authorization: Bearer {{accessToken}}

###