@API_HostAddress = https://localhost:7237
@Token = CfDJ8EYCB4DYsRJPkbRf642u2N2sB3rlBv8DEyXpLXZQheOAEzRy-__aNvW9OpebfwEBA7BkVgGgVfJiqyDdQQOfC109zuxyjq5qfpdoChPB7O6anmrbezltWTq-WZLV4Yufn7ky2LJA_m4GKc6jFNaXAj4gQPMr-c-ApDUkYUoNHLOQ3O4gs5a0oUJ6W_4z4yCaqKonC0k_0GAnOcSU1VGL8cLXMbcswcyNloIZlT-WYAr2d69z1iQmY-R1528XFl8iYlIGeyx2-ZwgNf84ZZA2UpdJvzx9J4cBNFH7kZGEW4TjuQj49JJuggrkAMfiRSs_JDgzMJTv97xlEcw7b6L36-eM5AsG13eecFEF5Scan8G826mUdt0RDACWJxlmUw_MOMN01tqPbEAR4GXBwG34aEYFHmb961tkACUr5-YaPVixFFPUl4L60Vk8D3K-SAb_sRAetNHnfGLRzzzPjBo8SOeP1wjE7yhXp4WFFY82Lq4K3eGglYPmZUl_FKyd9iZW8YHqSl7IukotObvGEh9c5GupG6mgLysw1T7dK6-Sph5CwkbAG_s-_z2hDXWjuDudycRv_begtyS8mk7o_-EAlGnqDgVvjLVPi0PBfr6iT8U_JxLNm2-ICpXb9jSZZ_35dDyf2gqPG-eHPtFEryZiikygL3BDOfhh9nzCUzsBg2jSxusfkPWS3fu8dcQ2IYt6Gw

POST {{API_HostAddress}}/login
Content-Type: application/json

{
  "email": "aloha@yopmail.com",
  "password": "Hello@123"
}

###

GET {{API_HostAddress}}/todo
Accept: application/json
Authorization: Bearer {{Token}}

###

POST {{API_HostAddress}}/todo
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "title": "Task 4",
  "date": "2024-02-29"
}

###
